variables:
  PLUGIN: 'availability_gwpayments'
  PATHNAME: 'availability/condition/gwpayments'
  REPOURL: 'https://github.com/sebsoftnl/moodle-availability_gwpayments'

include:
  - project: 'sebsoft/open-source/gitlab'
    file: '/opensource-plugin/opensource-plugin-405+.yml'
    ref: main
